Move git tag generation from makefile to here because of runtime eval issues in makefile (to be revisited)

diff --git a/bin/version-gen b/bin/version-gen
--- a/bin/version-gen
+++ b/bin/version-gen
@@ -1,37 +1,78 @@
 #!/bin/sh
 ds=`date +'%Y-%m-%d %T'`
-
+versds=`date +'%Y.%m.%d'`
 versionfile=version.php
+
+################################################################################
+git_update(){
+    # look for existing git tag with same name, if not, then add and commit
+    echo "Searching for existing git tags matching v$versds "
+    git tag | grep -E "^v$versds"
+    if [ $? -eq 0 ]; then
+        echo "tag by that name already found, skipping git tag"
+    else
+        echo "no tag with that name yet, committing version number and tag, "
+        git add $versionfile
+        git commit -m "Updating version number to $versds"
+        git tag -a v$versds -m "Updating version number to $versds"  
+        git push
+    fi
+}
+################################################################################
+version_prep(){
+    # try to get to the correct directory in case we are running from somewhere else
+    fullpath=`which $0`
+    if [ "$fullpath" ]; then
+        echo "fullpath = $fullpath"
+        dirn=`dirname $fullpath` 
+        cd $dirn
+        cd ..
+    fi
+    
+    # check that structure is legit
+    if test ! -d io -o ! -d bin  ; then
+        echo "moving up one dir"
+        cd ..
+        if test ! -d io -o ! -d bin  ; then
+            echo "cant seem to find the correct location for this to work"
+            exit
+        else
+            pwd
+            echo "seem to have found the right location"
+        fi
+    fi
+    
+    # verify that we have a version file to update
+    if [ ! -f $versionfile ]; then
+        echo "version file not found"
+        exit
+    fi
+}
+################################################################################
+create_version_file(){
+    yfile=`/bin/ls -rt *.php | grep -v version.php | tail -1`
+    echo "using command to generate: bin/datestamp-from-file $yfile"
+    versds=`bin/datestamp-from-file $yfile`
+    echo "got the following date string from $yfile: $versds"
+    chmod 644 $versionfile
+    printf "<?php\n  // version generated by $0 on $ds\n  \$GLOBALS['version'] = '$versds';\n?>\n" > $versionfile
+    chmod 644 $versionfile
+}
+################################################################################
+# main
+################################################################################
 if [[ $UID -ne 0 ]]; then
-  echo "using sudo to run $0"
-  sudo $0
-fi
-
-fullpath=`which $0`
-if [ "$fullpath" ]; then
-  echo "fullpath = $fullpath"
-  dirn=`dirname $fullpath` 
-  cd $dirn
-  cd ..
-fi
-
-if test ! -d io -o ! -d bin  ; then
-  echo "moving up one dir"
-  cd ..
-  if test ! -d io -o ! -d bin  ; then
-    echo "cant seem to find the correct location for this to work"
+    # want to run script via sudo
+    echo "using sudo to run $0"
+    sudo $0
+    
+    # the following will run as original user AFTER the script is run via sudo
+    version_prep
+    git_update
     exit
-  else
-    pwd
-    echo "seem to have found the right location"
-  fi
 fi
 
-date=`date +'%Y.%m.%d'`
-yfile=`/bin/ls -rt *.php | grep -v version.php | tail -1`
-echo "using command to generate: bin/datestamp-from-file $yfile"
-date=`bin/datestamp-from-file $yfile`
-echo "got the following date string from $yfile: $date"
-chmod 644 $versionfile
-printf "<?php\n  // version generated by $0 on $ds\n  \$GLOBALS['version'] = '$date';\n?>\n" > $versionfile
-chmod 644 $versionfile
+version_prep
+create_version_file
+
+
