php-8.2.x fixes

diff --git a/bin/version-gen b/bin/version-gen
--- a/bin/version-gen
+++ b/bin/version-gen
@@ -1,59 +1,50 @@
-#!/bin/sh
-ds=`date +'%Y-%m-%d %T'`
-versds=`date +'%Y.%m.%d'`
-versionfile=version.php
+#!/bin/bash
+ds=$(date +'%Y-%m-%d %T')
+versds=$(date +'%Y.%m.%d')
+
+# Adjust the following settings to reflect the repo being used
+versionfile='public_html/version.php'
+requiredDirs="public_html/inc public_html/tpl"
 
 ################################################################################
 git_update(){
     # look for existing git tag with same name, if not, then add and commit
-    echo "Searching for existing git tags matching v$versds "
+    echo "# Searching for existing git tags matching v$versds "
     git tag | grep -E "^v$versds"
     if [ $? -eq 0 ]; then
-        echo "tag by that name already found, skipping git tag"
+        echo "# Tag by that name already found, skipping git tag"
     else
-        echo "no tag with that name yet, committing version number and tag, "
+        echo "# Tag does not exist, committing version number and tag: ${versds}"
         git add $versionfile
         git commit -m "Updating version number to $versds"
         git tag -a v$versds -m "Updating version number to $versds"  
-        git push
+        # dont want to actually push here, lets leave that to the user
+        # git push
     fi
+}
+################################################################################
+dirs_exist(){
+    haveDirs='true'
+    for dir in $@; do
+        if [ ! -d "${dir}" ]; then
+            haveDirs='false'
+        fi
+    done
+    [ "${haveDirs}" = 'true' ] && return 0 || return 15
 }
 ################################################################################
 version_prep(){
-    # try to get to the correct directory in case we are running from somewhere else
-    fullpath=`which $0`
-    if [ "$fullpath" ]; then
-        echo "fullpath = $fullpath"
-        dirn=`dirname $fullpath` 
-        cd $dirn
-        cd ..
-    fi
-    
-    # check that structure is legit
-    if test ! -d io -o ! -d bin  ; then
-        echo "moving up one dir"
-        cd ..
-        if test ! -d io -o ! -d bin  ; then
-            echo "cant seem to find the correct location for this to work"
-            exit
-        else
-            pwd
-            echo "seem to have found the right location"
-        fi
-    fi
+    dirs_exist $requiredDirs || { echo "# Exiting because dirs dont exist"; exit 15; }
     
     # verify that we have a version file to update
-    if [ ! -f $versionfile ]; then
-        echo "version file not found"
-        exit
-    fi
+    [ ! -f $versionfile ] && { echo "# Version file not found"; exit 14; } 
 }
 ################################################################################
 create_version_file(){
-    yfile=`/bin/ls -rt *.php inc/*.php | grep -v version.php | tail -1`
-    echo "using command to generate: bin/datestamp-from-file $yfile"
-    versds=`bin/datestamp-from-file $yfile`
-    echo "got the following date string from $yfile: $versds"
+    lastest_mtime_file=$(/bin/ls -rt public_html/*.php public_html/inc/*.php | grep -v version.php | tail -1)
+    echo "# Generating datestamp from file using command: bin/datestamp-from-file.py $lastest_mtime_file"
+    versds=$(bin/datestamp-from-file.py $lastest_mtime_file)
+    echo "# Result: $lastest_mtime_file: $versds"
     chmod 644 $versionfile
     printf "<?php\n  // version generated by $0 on $ds\n  \$GLOBALS['version'] = '$versds';\n?>\n" > $versionfile
     chmod 644 $versionfile
@@ -61,18 +52,87 @@ create_version_file(){
 ################################################################################
 # main
 ################################################################################
-if [[ $UID -ne 0 ]]; then
-    # want to run script via sudo
-    echo "using sudo to run $0"
-    sudo $0
-    
-    # the following will run as original user AFTER the script is run via sudo
-    version_prep
-    git_update
-    exit
-fi
 
 version_prep
 create_version_file
+git_update
+
+
+# #!/bin/sh
+# ds=`date +'%Y-%m-%d %T'`
+# versds=`date +'%Y.%m.%d'`
+# versionfile=version.php
+
+# ################################################################################
+# git_update(){
+#     # look for existing git tag with same name, if not, then add and commit
+#     echo "Searching for existing git tags matching v$versds "
+#     git tag | grep -E "^v$versds"
+#     if [ $? -eq 0 ]; then
+#         echo "tag by that name already found, skipping git tag"
+#     else
+#         echo "no tag with that name yet, committing version number and tag, "
+#         git add $versionfile
+#         git commit -m "Updating version number to $versds"
+#         git tag -a v$versds -m "Updating version number to $versds"  
+#         git push
+#     fi
+# }
+# ################################################################################
+# version_prep(){
+#     # try to get to the correct directory in case we are running from somewhere else
+#     fullpath=`which $0`
+#     if [ "$fullpath" ]; then
+#         echo "fullpath = $fullpath"
+#         dirn=`dirname $fullpath` 
+#         cd $dirn
+#         cd ..
+#     fi
+    
+#     # check that structure is legit
+#     if test ! -d io -o ! -d bin  ; then
+#         echo "moving up one dir"
+#         cd ..
+#         if test ! -d io -o ! -d bin  ; then
+#             echo "cant seem to find the correct location for this to work"
+#             exit
+#         else
+#             pwd
+#             echo "seem to have found the right location"
+#         fi
+#     fi
+    
+#     # verify that we have a version file to update
+#     if [ ! -f $versionfile ]; then
+#         echo "version file not found"
+#         exit
+#     fi
+# }
+# ################################################################################
+# create_version_file(){
+#     yfile=`/bin/ls -rt *.php inc/*.php | grep -v version.php | tail -1`
+#     echo "using command to generate: bin/datestamp-from-file $yfile"
+#     versds=`bin/datestamp-from-file $yfile`
+#     echo "got the following date string from $yfile: $versds"
+#     chmod 644 $versionfile
+#     printf "<?php\n  // version generated by $0 on $ds\n  \$GLOBALS['version'] = '$versds';\n?>\n" > $versionfile
+#     chmod 644 $versionfile
+# }
+# ################################################################################
+# # main
+# ################################################################################
+# if [[ $UID -ne 0 ]]; then
+#     # want to run script via sudo
+#     echo "using sudo to run $0"
+#     sudo $0
+    
+#     # the following will run as original user AFTER the script is run via sudo
+#     version_prep
+#     git_update
+#     exit
+# fi
+
+# version_prep
+# create_version_file
 
 
